name: test
on: [push]
jobs:
  t:
    runs-on: ubuntu-latest
    container: library/busybox@sha256:d82f458899c9696cb26a7c02d5568f81c8c8223f8661bb2a7988b269c8b9051e
    steps:
      - uses: ${UNPINNED_ACTION}
